### PR TITLE
added snap-stride

### PR DESCRIPTION
**Pull request by gfudenberg**
option for snapping strides to a bp multiple for binned targets

### CODE REVIEW

**Comment by davek44** [comment]
Does basenji_data_4c_write.py do anything different from basenji_data_write.py?

I also wonder whether the differences between basenji_data_4c.py and basenji_data.py are enough to warrant two scripts with considerable overlap, or whether we can handle 4c with an option to basenji_data.py. I can take a stab at this next, because I'd like it to also cover basenji_data2.py for multiple genome mode.

**Comment by davek44** [comment]
Also, I think snap_stride is a bit of a misnomer. It doesn't really influence the strides; it's more about snapping the start position into line. From there, you just need to check if the stride is incompatible with the snap and tell the user to fix it.

**Comment by gfudenberg** [comment]
On Tue, Jun 18, 2019 at 4:33 PM David Kelley <notifications@github.com>
wrote:

> Does basenji_data_4c_write.py do anything different from
> basenji_data_write.py?
>
thought it might but turns out it doesn't!

> I also wonder whether the differences between basenji_data_4c.py and
> basenji_data.py are enough to warrant two scripts with considerable
> overlap, or whether we can handle 4c with an option to basenji_data.py. I
> can take a stab at this next, because I'd like it to also cover
> basenji_data2.py for multiple genome mode.
>
ya that would probably work. I guess the current thing in flux is what
flags basenji_data_4C_read.py will end up eating, which might vary a bunch
in the medium future

also-- looking at basenji_data2.py, I'm wondering if some of the
contig-generating stuff would be better migrated out into separate
functions (perhaps in an basenji/io/ or basenji/util/ folder)?

re: snap_stride, I'm happy with whatever name you think best. snap_to_bins?
binned_stride? The end of the stride is also snapped too in the current
version fwiw

>

**Comment by davek44** [comment]
Maybe snap_positions, snap_boundaries, snap_limits, or just snap :)

OK for now go with a separate basenji_data_4c.py, and we can clean them all up and ditch duplicated code once we know it's working. basenji_data2.py will have to change as well, if the way multiple genomes is handled changes.

**Comment by davek44** [comment]
Right now, you're correcting the sequence start, end, and stride with the snap. I think it'd be cleaner if you just return an error if the sequence length or stride is incompatible with the snap; the user will want more control over that. Once you've guaranteed that, you can just correct the starts for the snap, and the rest will fall into place cleanly.

**Pull request merged**
